### ISSUE TITLE
Still having issues after attempting to use 1.1.1.zip

### ISSUE THREAD

**Issue by jouster1974** [kuglee/TermiWatch#6]
have had both previous isues mentioned by others and the 1.1.1 zip hasnt fixed things fully.

Attempting install on 12.2 phone and 5.2, latest dev betas on both

With the 1.1.1 file I am getting the "module compiled with swift 4.2.1 cannot be imported by swift 5.0 compiler

**Comment by kuglee** [comment]
Please use this version:
https://github.com/kuglee/TermiWatch/releases/download/1.1.1_Chartage/TermiWatch_1.1.1_Carthage.zip

**Comment by jouster1974** [comment]
Trying it next.  Thanks

**Comment by jouster1974** [comment]
couple of different errors now

1st:-     linker command failed with esit code 1 (use -v to see invocation
2nd:-   command CompileSwift failed with a nonzero exit code

thanks again for you assistance and updates

**Comment by shinytreecko** [comment]
App installed correctly with the version you included in the link above for my iPhone running on iOS 12.1.1 beta 3 and my Apple Watch running on WatchOS 5.1.4. My only problem is that when I launch the app on my watch, I can't see my activity data, steps, or heart rate. I'm assuming it's an error for health kit but I don't know how to fix it. Any ideas that I could try? In Xcode I get this message at the bottom of the screen right when I ran the app on my phone for the first time

CoreFoundation = 1561.000000
Could not match CoreFoundation = 1561.000000
2019-03-17 13:57:45.745655-0400 TermiWatch[1260:45350] [Accessibility] ****************** Loading GAX Client Bundle ****************
Error: Error Domain=com.apple.healthkit Code=100 "Rolling back the health database is unsupported." UserInfo={NSLocalizedDescription=Rolling back the health database is unsupported.}
Message from debugger: Terminated due to signal 9

**Comment by jouster1974** [comment]
Dis you mean to launch a new issue for devs attention?

**Comment by kuglee** [comment]
@shinytreecko This is what I've found: https://stackoverflow.com/questions/44903407/error-while-authorization-to-healthkit-code-100-rolling-back-the-health-datab

This can happen if you restored to a previous iOS version. I don't know how to fix it unfortunately.

**Comment by kuglee** [comment]
@jouster1974 Did you change the the dev account in the project? Try cleaning the project (XCode menu -> Product -> Clean)

**Comment by jouster1974** [comment]
yes followed instructions as written...never had an issues on any other builds of oter face apps before.

tried the clea command and same issues persists

**Comment by jouster1974** [comment]
now all working well..many thanks for all of your assistance...the only slight issue I saw was that when I change time format to HH:MM:SS, for some reason either the seconds dont change (whilst the watch facce is active) or the time with that exact format is wrong but about 25 minutes....couldnt ork out why so just went back to HH:MM

Loving the face and have had a few small ideas for ways to improve things.  I am not a dev in any way though so forgive me for making odd or crazy suggestions.

I have managed to mod the face nicely giving me some pretty cool extra detail and also some monograms.

If the phone app (which it looks like is really just for installing the watch app) would allow you to change some of the settings like formats, colours and a few lines of text...that would be an awesome addition to an already great face as it would mean not needing to rebuild the app each time


![IMG_5265](https://user-images.githubusercontent.com/15368005/54538575-6594a400-498c-11e9-9943-6e3cb48a2440.PNG)
![IMG_5264](https://user-images.githubusercontent.com/15368005/54538576-6594a400-498c-11e9-91b0-c8b1ca2c4e30.JPG)

**Comment by jouster1974** [comment]
my final version....I think

![IMG_5269](https://user-images.githubusercontent.com/15368005/54547452-a5b05280-499d-11e9-8810-cb2155a1e54d.JPG)

**Comment by pllgit** [comment]
When I open the app on my phone all I see is a white screen.

**Comment by shinytreecko** [comment]
I have the same issue as pllgit. Not sure if the app is intentionally just a white screen or not, however.

**Comment by lowe-wesley** [comment]
The iPhone app will be just all white - the only thing you should get is request to access location and HealthKit data on the initial launch.  After that it, is just a white screen.

> I have the same issue as pllgit. Not sure if the app is intentionally just a white screen or not, however.

**Comment by jouster1974** [comment]
Happy to close off this issue for now
